a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Bitwise Operators")
print("-----------------")
print("AND  (a & b)  :", a & b)
print("OR   (a | b)  :", a | b)
print("XOR  (a ^ b)  :", a ^ b)
print("NOT  (~a)     :", ~a)
print("Left Shift  (a << 1) :", a << 1)
print("Right Shift (a >> 1) :", a >> 1)
